
development:
  TWITTER_KEY: 'UWC1Z3BYQ9GGNg1ixBiVJw'
  TWITTER_SECRET: 'ZimTPG4Cj19ETvkmPZusPKHaHN975CbIqnPrEgYXw8'

  FACEBOOK_APP_ID: '423468787678045'
  FACEBOOK_SECRET: '9149b132fc2dc63a2b0c582c3f68da41'

  MAIL_NOREPLY: 'no-reply@creasty.com'

  GOOGLE_API_KEY: 'AIzaSyCv3Fh19Z8Fc15ZiwQqw06Wh4q28MyzCP0'
  GOOGLE_USERNAME: 'ykiwng@gmail.com'
  GOOGLE_PASSWORD: 'kytwqsetmodzecqz'
  GOOGLE_ANALYTICS_USERAGENT: 'UA-4498942-3'

