
development:
  TWITTER_KEY: 'UWC1Z3BYQ9GGNg1ixBiVJw'
  TWITTER_SECRET: 'ZimTPG4Cj19ETvkmPZusPKHaHN975CbIqnPrEgYXw8'

  FACEBOOK_APP_ID: '423468787678045'
  FACEBOOK_SECRET: '9149b132fc2dc63a2b0c582c3f68da41'

